### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by masternachiket** [sdabhi23/bsedata#22]
After fetching quotes for few companies it shows AttributeError.

```
Traceback (most recent call last):
  File "data.py", line 121, in <module>
    get_data()
  File "data.py", line 14, in get_data
    quote = b.getQuote(company_code)
  File "/home/masternachiket/anaconda3/envs/Trader/lib/python3.6/site-packages/bsedata/bse.py", line 60, in getQuote
    return quote.quote(scripCode)
  File "/home/masternachiket/anaconda3/envs/Trader/lib/python3.6/site-packages/bsedata/quote.py", line 47, in quote
    res['change'] = span.string.split('(')[0].strip()
AttributeError: 'NoneType' object has no attribute 'split'


```

**Comment by fengmingming-ail** [comment]
请问您是否解决了此问题，我也遇到了同样问题

**Comment by sdabhi23** [comment]
Can you please share the scrip code for which you are getting this error?
