### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by fengmingming-ail** [sdabhi23/bsedata#23]
----------------------------------------
Exception happened during processing of request from ('171.126.61.220', 60999)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 333, in send_headers
    self._write(bytes(self.headers))
  File "/usr/local/python3/lib/python3.7/wsgiref/headers.py", line 142, in __bytes__
    return str(self).encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 139-140: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/root/.virtualenvs/django/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 88, in handle_error
    super(ServerHandler, self).handle_error()
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/socketserver.py", line 647, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/python3/lib/python3.7/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/python3/lib/python3.7/socketserver.py", line 717, in __init__
    self.handle()
  File "/root/.virtualenvs/django/lib/python3.7/site-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/local/python3/lib/python3.7/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/local/python3/lib/python3.7/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by sdabhi23** [comment]
Can you please share the scrip code for which you are getting this error?

**Comment by sdabhi23** [comment]
Closing due to inactivity, Please open a new issue with more details if you are still facing this issue
