### ISSUE TITLE
json Error while fetching historic data

### ISSUE THREAD

**Issue by avidekar** [sdabhi23/bsedata#42]
from bsedata.bse import BSE
b = BSE(update_codes = True)
b.getPeriodTrend('524804', '12M')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Askanksha\AppData\Roaming\Python\Python310\site-packages\bsedata\bse.py", line 111, in getPeriodTrend
    return periodTrend.getPeriodTrend(scripCode, timePeriod)
  File "C:\Users\Askanksha\AppData\Roaming\Python\Python310\site-packages\bsedata\periodTrend.py", line 45, in getPeriodTrend
    data = json.loads(res.content.decode('utf-8'))
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 4)

Anyone else seeing this issue?
I am using 3.10.10 python version

**Comment by avidekar** [comment]
this one is duplicate. Closing this one.
