### ISSUE TITLE
airtel data is not avaialble, getting error

### ISSUE THREAD

**Issue by ashwin31** [sdabhi23/bsedata#51]
from bsedata.bse import BSE
from pprint import pprint

b = BSE(update_codes = True)

q = b.getQuote('890157')
pprint(q)

**Comment by ashwin31** [comment]
erro is
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    q = b.getQuote('890157')
  File "/home/ubuntu/env/lib/python3.8/site-packages/bsedata/bse.py", line 61, in getQuote
    return quote.quote(scripCode)
  File "/home/ubuntu/env/lib/python3.8/site-packages/bsedata/quote.py", line 87, in quote
    res['industry'] = td.string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
